url: "https://ryankshah.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ryan K. Shah" # the name of your site, e.g. ACME Corp.
description: "Academic Website for Ryan K. Shah, Ph.D., AFHEA, BSc (Hons)"
theme: academic-jekyll-theme